media:
  input: ""
  output: ""

content:
  - name: duyurular
    label: Duyurular Panosu
    type: collection
    path: duyurular
    format: json
    fields:
      - name: baslik
        label: Duyuru Basligi
        type: string
        required: true
      - name: kategori
        label: Kategori
        type: string
      - name: tarih_saat
        label: Tarih ve Saat
        type: string
      - name: aciklama
        label: Aciklama
        type: text
      - name: resim
        label: Afis Resmi
        type: image
      - name: form_linki
        label: Form Linki
        type: string
      - name: belge_linki
        label: Belge Linki
        type: string